### ISSUE TITLE
verification fails for the simple MM example

### ISSUE THREAD

**Issue by jinz2014** [ROCm/rocWMMA#387]
The HIP example at https://github.com/zjin-lcf/HeCBench/tree/master/src/wmma-hip is similar to codes in https://rocm.docs.amd.com/projects/rocWMMA/en/latest/API_Reference_Guide.html:

The matrices A and B are of type float16 while the matrices C and D are of float32. However, the verification fails for the example after the host GEMM is added for validation.

```
// Host GEMM validation
void gemm_cpu_h(uint32_t m, uint32_t n, uint32_t k, rocwmma::float16_t const *a,
                rocwmma::float16_t const *b, rocwmma::float32_t const *c, rocwmma::float32_t *d,
                uint32_t lda, uint32_t ldb, uint32_t ldc, uint32_t ldd,
                rocwmma::float32_t alpha, rocwmma::float32_t beta) {
  for (uint32_t i = 0; i < m; ++i) {
    for (uint32_t j = 0; j < n; ++j) {
      rocwmma::float32_t accum = 0.0f;
      for (uint32_t h = 0; h < k; ++h) {
        accum += static_cast<rocwmma::float32_t>(a[i * lda + h]) *
                 static_cast<rocwmma::float32_t>(b[j * ldb + h]);
      }
      d[i * ldd + j] = alpha * accum + beta * c[i * ldc + j];
    }
  }
}
```
It is successful for the CUDA example (https://github.com/zjin-lcf/HeCBench/tree/master/src/wmma-cuda). 

I am not sure if there are issues in the example or library. Thank you.

**Comment by dlangbe** [comment]
Hello Jin, thank you for reaching out!
 
For this particular issue, we will require more information - much like from the given template in the Issue Discussion section of the [Contributing Guide](https://github.com/ROCm/rocWMMA/blob/develop/CONTRIBUTING.md). Please provide information on your OS, GPU, and ROCm version for us to get started investigating. Thank you!

**Comment by jinz2014** [comment]
5.15.0-105-generic Ubuntu SMP
gfx908
hipcc --version
HIP version: 6.0.32831-204d35d16
AMD clang version 17.0.0 (https://github.com/RadeonOpenCompute/llvm-project roc-6.0.2 24012 af27734ed982b52a9f1be0f035ac91726fc697e4)
Target: x86_64-unknown-linux-gnu
 
Thanks.

**Comment by dlangbe** [comment]
I tested your HIP sample on gfx908 and had to change WAVE_SIZE from 32 to 64 to get the expected output. Let me know if that works for you.

**Comment by jinz2014** [comment]
That works on gfx908.

I also tried to run the example on a gfx1030 device. 
When the WAVE_SIZE is 32, the output is
./main 256 256 256 100 1
Max relative error: nan


When the size is 64, the output is 
./main 256 256 256 100 1
Max relative error: 0.999846

HIP version: 6.0.32830-d62f6a171
AMD clang version 17.0.0 (https://github.com/RadeonOpenCompute/llvm-project roc-6.0.0 23483 7208e8d15fbf218deb74483ea8c549c67ca4985e)

6.5.0-28-generic #29~22.04.1-Ubuntu

Thanks

**Comment by dlangbe** [comment]
rocWMMA does not support gfx1030, only gfx11+ for RDNA.
