### ISSUE TITLE
[Feature]: Compile for Windows library 

### ISSUE THREAD

**Issue by sorasoras** [ROCm/rocWMMA#391]
### Suggestion Description

I tried to build rocwmma for windows to use in llama cpp but I cannot find any documentation.
rocm 5.7.1 does not seems have rocwmma support.

### Operating System

Windows11

### GPU

7900XTX

**Comment by cgmillette** [comment]
Hello @sorasoras, thanks for reaching out!

The documentation for ROCm 5.7.1 regarding rocWMMA is [here](https://rocm.docs.amd.com/projects/rocWMMA/en/docs-5.7.1/index.html).

Just a couple of notes:
- rocWMMA is not officially supported on Windows yet.
- rocWMMA is a header library.

The library has been written in a way that should be friendly to most compilers. One might try to use rocWMMA on Windows by providing the include path and platform-related flags to their ROCm compiler. It may require a few minor changes but not impossible.

**Comment by sorasoras** [comment]
> Hello @sorasoras, thanks for reaching out!
> 
> The documentation for ROCm 5.7.1 regarding rocWMMA is [here](https://rocm.docs.amd.com/projects/rocWMMA/en/docs-5.7.1/index.html).
> 
> Just a couple of notes:
> 
> * rocWMMA is not officially supported on Windows yet.
> * rocWMMA is a header library.
> 
> The library has been written in a way that should be friendly to most compilers. One might try to use rocWMMA on Windows by providing the include path and platform-related flags to their ROCm compiler. It may require a few minor changes but not impossible.

I am trying to compile it

```
cmake .. -G "Ninja" -DROCWMMA_BUILD_TESTS=OFF -DROCWMMA_BUILD_SAMPLES=OFF -DCMAKE_C_COMPILER="C:/Program Files/AMD/ROCm/5.7/bin/clang.exe" -DCMAKE_CXX_COMPILER="C:/Program Files/AMD/ROCm/5.7/bin/clang++.exe" -DAMDGPU_TARGETS="gfx1100"
-- The CXX compiler identification is Clang 17.0.0 with GNU-like command-line
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/AMD/ROCm/5.7/bin/clang++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:67 (find_package):
  Could not find a package configuration file provided by "ROCM" (requested
  version 0.7) with any of the following names:

    ROCMConfig.cmake
    rocm-config.cmake

  Add the installation prefix of "ROCM" to CMAKE_PREFIX_PATH or set
  "ROCM_DIR" to a directory containing one of the above files.  If "ROCM"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
```

What do I miss?

**Comment by ppanchad-amd** [comment]
Hi @sorasoras, internal ticket has been created to assist with your issue. Thanks!

**Comment by tcgu-amd** [comment]
HI @sorasoras, sorry for the lack of response. As @cgmillette mentioned, ROCm is not natively supported on Windows 11 yet. The error you are getting seem to be related to missing dependencies from ROCm, likely rocm-cmake from https://rocm.docs.amd.com/projects/rocWMMA/en/docs-6.2.0/install/installation.html#dependencies. Please note that in addition to this dependency, it also requires rocm-smi-lib to compile.

**Comment by sorasoras** [comment]
> HI @sorasoras, sorry for the lack of response. As @cgmillette mentioned, ROCm is not natively supported on Windows 11 yet. The error you are getting seem to be related to missing dependencies from ROCm, likely rocm-cmake from https://rocm.docs.amd.com/projects/rocWMMA/en/docs-6.2.0/install/installation.html#dependencies. Please note that in addition to this dependency, it also requires rocm-smi-lib to compile.

thanks for the response.
it seems like it would be very difficult to get it working on windows right now

**Comment by tcgu-amd** [comment]
@sorasoras Unfortunately, that seem to be the case right now. The best alternative right now is try to get it to run on WSL. In the meantime, since there seem to be no longer any actionable item at the moment, I will be closing this issue for now. Thanks!
