### ISSUE TITLE
Question: can I use rocWMMA to leverage Matrix Core on rocm5.7.1?

### ISSUE THREAD

**Issue by tiandi111** [ROCm/rocWMMA#426]
### Problem Description

As described in the title, can I use  rocWMMA to leverage Matrix Core on rocm5.7.1?

If not, is there any way to use Matrix Core in my own hand written kernel on rocm5.7.1?

### Operating System

Ubuntu 22.04.4 LTS (Jammy Jellyfish)

### CPU

Intel(R) Xeon(R) Platinum 8352Y CPU @ 2.20GHz

### GPU

AMD Instinct MI210

### ROCm Version

ROCm 5.7.1

**Comment by cgmillette** [comment]
Hi @tiandi111 , yes - please refer to the release tag [here](https://github.com/ROCm/rocWMMA/tree/rocm-5.7.1)
